### ISSUE TITLE
Viz for Manuscript

### ISSUE THREAD

**Issue by AMGold99** [AMGold99/fmv#12]
Thread to flag/discuss any viz needed for the manuscript
---
Viz Sections Checklist
- [x] County-level results from full model
- [x] County: compare nolte county base to nolte county hpi
- [x] County: Variable Importance from full model
- [ ] FRR results from full model
- [x] FRR: compare nolte v. full in terms of: added coverage; accuracy; comparison between performance in <1000 obs counties (this requires getting a list of <1000 counties from the county models)
- [x] FRR: Variable importance from full model
- [ ] FRR: performance in only "added" counties (relative to county level)
- [x] Across geo scales: compare parcel-level MSE
- [x] Performance as a function of observation density
- [ ] Predictive power over time: MSE v. time, w/ and w/o HPI, within training sample year range; MSE and R^2 w/ and w/o HPI in 2020

**Comment by binders1** [comment]
Small issue: I think we should use a unique color scale for each of the MSE maps in Fig 4

**Comment by AMGold99** [comment]
> Small issue: I think we should use a unique color scale for each of the MSE maps in Fig 4

As in, give each one its own palette? Would that affect the reader's ability to compare the two?

**Comment by binders1** [comment]
Yes, I was thinking different palettes. It seems like using the same
palette but with different mappings of value to color can be confusing or
misleading.

Seth Binder, PhD
Associate Professor of Economics and Environmental Studies
Chair of Environmental Studies
St. Olaf College

Website <https://www.stolaf.edu/profile/binder/>, LinkedIn
<http://www.linkedin.com/in/seth-binder-30b1072>


*Appointment page
<https://calendar.google.com/calendar/selfsched?sstoken=UURqd0M3VzdDNTYxfGRlZmF1bHR8MzI5ZmE1MGUyNDgyNzYzY2EzZDAwNTRjZmQxMDI0NDk>*

**Comment by AMGold99** [comment]
That makes sense, I’m in agreement there. Thanks for making a note of it.

Asa Gold

**Comment by AMGold99** [comment]
- [ ] @AMGold99 Reorganize viz code scripts and output/figure dir
